eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9001
spring:
  application:
    name: spring-cloud-producer
  redis:
    database: 4
    host: 192.168.1.101
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
    port: 6379
    timeout: 0