# Site settings
name: xqw的个人博客
email: 773532049@qq.com
author: xqw
url: http://glowwormX.github.io
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/glowwormX/
baseurl: ""
#description: Actually, less is more!
meta_description: xqw的个人博客
#motto: It's our wits that make us men.
#banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: glowwormX

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

