eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9600
spring:
  application:
    name: zipkin-server
  zipkin:
    base-url: http://localhost:9600
  sleuth:
    sampler:
      percentage: 1.0