logging:
  level:
    root: info
  path: log
  file:
    max-size: 100MB #单个日志文件大小
    max-history: 30 #日志文件保存30天的
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.77:3306/mbxt-sync?characterEncoding=UTF-8
#    username: xqw
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
#    sql-script-encoding: utf-8
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
#    hibernate:
#      ddl-auto: update